# Generated by Django 6.0.4 on 2026-04-16 21:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Name of your skill or service (e.g., 'Python Tutoring')", max_length=200)),
                ('description', models.TextField(help_text="Detailed description of what you're offering")),
                ('category', models.CharField(choices=[('tutoring', 'Tutoring'), ('design', 'Design'), ('tech', 'Technology'), ('sports', 'Sports'), ('music', 'Music'), ('language', 'Language'), ('fitness', 'Fitness'), ('business', 'Business'), ('creative', 'Creative'), ('other', 'Other')], default='other', help_text='What category does your skill fall into?', max_length=50)),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('negotiable', 'Negotiable')], default='negotiable', help_text='Is your skill free or paid?', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price (leave blank if free)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], default='email', help_text='How should people contact you?', max_length=20)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('pending', 'Pending')], default='available', help_text='Are you currently available?', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user offering this skill', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'ordering': ['-created_at'],
            },
        ),
    ]
